[package]
name = "psonoci"
version = "0.1.0"
authors = ["Bernd Kaiser <bk@dfjk.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
attohttpc = { version = "0.14.0", default-features = false, features = ["tls-rustls", "json"] }
clap = "2.33.1"
hex = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.15"
url = "2.1.1"
uuid = "0.8.1"
xsalsa20poly1305 = "0.4.2"
