[build.env]
passthrough = [
    "RUSTFLAGS",
]
#[target.armv7-unknown-linux-musleabihf]
#image = "psonoci_builder:armv7-unknown-linux-musleabihf"
#
#[target.armv7-unknown-linux-gnueabihf]
#image = "psonoci_builder:armv7-unknown-linux-gnueabihf"
#
#[target.aarch64-unknown-linux-musl]
#image = "psonoci_builder:aarch64-unknown-linux-musl"
#
#[target.aarch64-unknown-linux-gnu]
#image = "psonoci_builder:aarch64-unknown-linux-gnu"
#
#[target.x86_64-unknown-linux-musl]
#image = "psonoci_builder:x86_64-unknown-linux-musl"
#
#[target.x86_64-pc-windows-gnu]
#image = "psonoci_builder:x86_64-pc-windows-gnu"