FROM rustembedded/cross:armv7-unknown-linux-musleabihf

COPY build_openssl.sh /
RUN bash /build_openssl.sh linux-generic32 arm-linux-musleabihf-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    OPENSSL_STATIC=1 \
    TARGET=musl