FROM rustembedded/cross:aarch64-unknown-linux-gnu

COPY build_openssl.sh /
# first parameter is the openssl arch target (see openssls ./Configure LIST)
RUN bash /build_openssl.sh linux-aarch64 aarch64-linux-gnu-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    OPENSSL_STATIC=1