FROM rustembedded/cross:x86_64-unknown-linux-musl

# sets -DOPENSSL_NO_SECURE_MEMORY during ./Configure
# taken from rust-musl-builder
ENV NO_SECURE_MEMORY=1

COPY build_openssl.sh /
# first parameter is the openssl arch target (see openssls ./Configure LIST)
RUN bash /build_openssl.sh linux-x86_64 x86_64-linux-musl-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    OPENSSL_STATIC=1 \
    TARGET=musl