name: Build
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            builder_image: meldron/psonoci_builder
        strategy:
            matrix:
                target:
                    - x86_64-unknown-linux-musl
                    - aarch64-unknown-linux-musl
                    - armv7-unknown-linux-gnueabihf
                    - x86_64-pc-windows-gnu

        steps:
            - name: Get the version
              id: get_version
              run: echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true

            - name: Pull docker image used by cross
              if: matrix.target != 'x86_64-pc-windows-gnu'
              run: docker pull $builder_image:${{ matrix.target }}

            # # right now do not build image every time to save github actions quota
            - name: Build docker image used by cross
              if: matrix.target != 'x86_64-pc-windows-gnu'
              run: docker build build_files --cache-from $builder_image:${{ matrix.target }} --file build_files/Dockerfile-${{ matrix.target }} --tag $builder_image:${{ matrix.target }}

            - name: cargo fmt
              uses: actions-rs/cargo@v1
              with:
                  use-cross: false
                  command: fmt
                  args: --all -- --check

            - name: cargo test
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: test
                  args: --release --target ${{ matrix.target }}

            - name: cargo build
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target ${{ matrix.target }}

            - name: upload unix artifact
              uses: actions/upload-artifact@v2
              if: matrix.target != 'x86_64-pc-windows-gnu'
              with:
                  name: psonoci-${{ env.SHA8 }}-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/psonoci

            - name: upload windows artifact
              uses: actions/upload-artifact@v2
              if: matrix.target == 'x86_64-pc-windows-gnu'
              with:
                  name: psonoci-${{ env.SHA8 }}-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/psonoci.exe
