name: Release
on:
    push:
        branches:
            - debug/release
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    # build-macos:
    #     runs-on: macos-latest
    #     steps:
    #         - uses: actions/checkout@v2

    #         - uses: actions-rs/toolchain@v1
    #           with:
    #               toolchain: stable

    #         - uses: actions-rs/cargo@v1
    #           with:
    #               command: build
    #               args: --release

    #         - uses: actions/upload-artifact@v2
    #           with:
    #               name: psonoci-${GITHUB_SHA::8}-x86_64-apple-darwin
    #               path: target/release/psonoci
    build:
        runs-on: ${{ matrix.os }}
        env:
            builder_image: meldron/psonoci_builder
            SHA8: $(git rev-parse --short=8 ${{ github.sha }})
        strategy:
            matrix:
                build: [linux, linux-armv7, linux-aarch64, macos, win-gnu]
                include:
                    - build: linux
                      os: ubuntu-18.04
                      target: x86_64-unknown-linux-musl
                    - build: linux-armv7
                      os: ubuntu-18.04
                      target: armv7-unknown-linux-musleabihf
                    - build: linux-aarch64
                      os: ubuntu-18.04
                      target: aarch64-unknown-linux-musl
                    - build: macos
                      os: macos-latest
                      target: x86_64-apple-darwin
                    - build: win-gnu
                      os: ubuntu-18.04
                      target: x86_64-pc-windows-gnu

        steps:
            - name: Get sha8
              id: get_sha8
              run: echo "::set-env name=SHA8::$(echo ${GITHUB_SHA} | cut -c1-8)"

            - name: Get the release version from the tag
              if: env.VERSION == ''
              run: |
                  # taken from https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml
                  # Apparently, this is the right way to get a tag name. Really?
                  #
                  # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
                  echo "::set-env name=VERSION::${GITHUB_REF#refs/tags/}"
                  echo "version is: ${{ env.VERSION }}"

            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true

            - name: Pull docker image used by cross
              if: matrix.target != 'x86_64-pc-windows-gnu' && matrix.target != 'x86_64-apple-darwin'
              run: docker pull $builder_image:${{ matrix.target }}

            # - name: Build docker image used by cross
            #   if: matrix.target != 'x86_64-pc-windows-gnu'
            #   run: docker build build_files --cache-from $builder_image:${{ matrix.target }} --file build_files/Dockerfile-${{ matrix.target }} --tag $builder_image:${{ matrix.target }}

            - uses: actions-rs/cargo@v1
              if: matrix.os == 'ubuntu-18.04'
              with:
                  use-cross: true
                  command: build
                  args: --release --target ${{ matrix.target }}

            - uses: actions-rs/cargo@v1
              if: matrix.os != 'ubuntu-18.04'
              with:
                  use-cross: false
                  command: build
                  args: --release --target ${{ matrix.target }}

            - uses: actions/upload-artifact@v2
              if: matrix.target != 'x86_64-pc-windows-gnu'
              with:
                  name: psonoci-${{ env.SHA8 }}-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/psonoci

            - uses: actions/upload-artifact@v2
              if: matrix.target == 'x86_64-pc-windows-gnu'
              with:
                  name: psonoci-${{ env.SHA8 }}-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/psonoci.exe
